const modules=[['dashboard','Dashboard'],['clients','Clients'],['client','Client Information'],['appointments','Appointments'],['communications','Communications'],['notifications','Notifications'],['documents','Documents'],['medicare','Medicare'],['life','Life'],['retirement','Retirement'],['agents','Agents & Admin'],['settings','Settings']];
const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function route(){const r=location.hash.replace(/^#\/?/,'')||'dashboard';return modules.some(x=>x[0]===r)?r:'dashboard'}
function nav(active){return modules.map(([id,label])=>`<button data-route="${id}" class="${active===id?'active':''}">${esc(label)}</button>`).join('')}
function shell(id,body){const label=modules.find(x=>x[0]===id)?.[1]||'Dashboard';app.innerHTML=`<div class="shell"><aside class="sidebar" id="sidebar"><div class="brand">M&amp;H CRM<small>Insurance Group</small></div><div class="nav">${nav(id)}</div></aside><main class="main"><header class="top"><button class="secondary mobile" id="menu">☰</button><h1>${label}</h1><div class="spacer"></div><span class="pill">Framework • No Live Data</span><button class="primary" data-route="client">Add Client</button></header><div class="content">${body}</div></main></div>`;bind()}
const banner=()=>`<div class="banner"><b>Standalone M&amp;H CRM framework.</b> No fake clients, policies, appointments, messages, documents, or sample records are included. Database, authentication, storage, RingCentral, and App Store packaging are intentionally disconnected.</div>`;
const metric=(t)=>`<div class="card metric"><span class="muted">${t}</span><b>—</b><span class="muted">No live data connected</span></div>`;
const empty=(title,copy)=>`<div class="card empty"><div><h3>${title}</h3><div class="muted">${copy}</div></div></div>`;
const status=(icon,name,copy,state='Not connected',ready=false)=>`<div class="status-row"><i>${icon}</i><div><strong>${name}</strong><div class="muted">${copy}</div></div><span class="tag ${ready?'ready':''}">${state}</span></div>`;
function dashboard(){return `${banner()}<div class="grid four">${metric('Clients')}${metric('Appointments')}${metric('Notifications')}${metric('Documents')}</div><h2 class="section-title">Quick Actions</h2><div class="grid four"><div class="card quick" data-route="client"><strong>Client Information</strong><span class="muted">Open the new-client framework.</span></div><div class="card quick" data-route="clients"><strong>Search Clients</strong><span class="muted">Search-first; no records load automatically.</span></div><div class="card quick" data-route="appointments"><strong>Appointments</strong><span class="muted">Calendar and follow-up workspace.</span></div><div class="card quick" data-route="communications"><strong>Communications</strong><span class="muted">Calls, text, and email workspace.</span></div></div><h2 class="section-title">System Readiness</h2><div class="grid two"><div class="card"><div class="status">${status('UI','Responsive shell','Desktop, tablet, iPhone and Android layouts','Ready',true)}${status('⌕','Search-first clients','Client list remains empty until searched','Ready',true)}${status('DATE','Manual dates','MM/DD/YYYY text entry','Ready',true)}</div></div><div class="card"><div class="status">${status('DB','Database','New standalone M&H database')}${status('FILE','File Storage','Separate client document storage')}${status('RC','RingCentral','Calls, SMS and recordings')}${status('','iOS App','TestFlight and App Store packaging')}</div></div></div>`}
function clients(){return `${banner()}<div class="card"><h2>Client Search</h2><p class="muted">No clients populate automatically. Search or filter after the standalone database is connected.</p><div class="toolbar"><input placeholder="Name, phone, email, DOB, address, ZIP…"><select><option>All Products</option><option>Medicare</option><option>Life</option><option>Retirement</option></select><select><option>All Agents</option></select><button class="secondary" data-demo>Search</button><button class="secondary" data-demo>Turn 65</button></div></div><div style="height:14px"></div>${empty('No client results displayed','This is intentional. There are no test or sample clients in M&H CRM.')}`}
const field=(label,ph='',cls='')=>`<div class="field ${cls}"><label>${label}</label><input placeholder="${ph}"></div>`;
const date=(label)=>field(label,'MM/DD/YYYY');
function client(){return `${banner()}<div class="form-sections"><details open><summary>Client Information</summary><div class="form">${field('First Name')}${field('Last Name')}${date('Date of Birth')}<div class="field"><label>Gender</label><select><option>Select…</option><option>Male</option><option>Female</option></select></div>${field('Email')}${field('Phone','(###) ###-####')}${field('Address','', 'span2')}${field('City')}${field('County')}${field('State')}${field('ZIP Code')}${field('Social Security Number','Encrypted when backend is connected')}${field("Driver's License Number",'Encrypted when backend is connected')}${date("Driver's License Expiration")}<div class="field"><label>License State</label><input></div><div class="field span4"><label>Products</label><div class="checks"><label class="check"><input type="checkbox"> Medicare</label><label class="check"><input type="checkbox"> Life</label><label class="check"><input type="checkbox"> Retirement</label></div></div></div></details><details><summary>Medicare Information</summary><div class="form">${field('Medicare Number')}${date('Part A Date')}${date('Part B Date')}${field('Medicaid Number')}<div class="field"><label>Medicaid Level</label><select><option>Select…</option><option>QMB</option><option>SLMB</option><option>FBDE</option></select></div><div class="field span4"><label>Files / Card Photos</label><input type="file" disabled><span class="muted">Storage not connected yet.</span></div></div></details><details><summary>Health Plan Information</summary><div class="form">${field('Carrier')}${field('Plan ID')}${field('Member ID')}${date('Effective Date')}</div></details><details><summary>Notes</summary><div class="form"><div class="field span4"><label>Client Notes</label><textarea placeholder="Notes will save after the standalone database is connected."></textarea></div></div></details></div><div style="text-align:right;margin-top:14px"><button class="primary" data-demo>Save Client</button></div>`}
function appointments(){return `${banner()}${empty('No appointments','Calendar framework is ready. No fake appointments were added.')}`}
function communications(){return `${banner()}<div class="grid two"><div class="card"><h2>Communications Workspace</h2><div class="status">${status('RC','RingCentral Voice','Inbound/outbound calling')}${status('SMS','RingCentral SMS','Individual and selected-client messaging')}${status('REC','Call Recordings','Automatic client matching and storage')}</div></div>${empty('No conversation selected','No messages, calls, contacts, or recordings are included.')}</div>`}
function notifications(){return `${banner()}${empty('No notifications','This area will show form submissions, assignments, communication events, and CRM activity after services are connected.')}`}
function documents(){return `${banner()}<div class="grid two"><div class="card"><h2>Client Documents</h2><div class="status">${status('SOA','Scope of Appointment','Signed Medicare SOA documents')}${status('DOC','Policy Documents','Coverage and policy files')}${status('IMG','Card / Photo Imports','Computer file, camera and mobile intake')}</div></div>${empty('Document storage is empty','No sample files were added.')}</div>`}
function product(type){const copy={medicare:'Medicare numbers, Part A/B dates, Medicaid data, plan details, SOA documents and files.',life:'Life policy records, carrier, product, face amount, premium, dates, notes and documents.',retirement:'Retirement products, contract information, carrier details, contributions, dates, notes and documents.'}[type];return `${banner()}<div class="card"><h2>${type[0].toUpperCase()+type.slice(1)} Module</h2><p class="muted">${copy}</p></div><div style="height:14px"></div>${empty(`No ${type} records`,'Records will appear only after the standalone database is connected and real entries are created.')}`}
function agents(){return `${banner()}<div class="card"><h2>Role Framework</h2><div class="grid four"><div class="card"><b>Owner</b><p class="muted">Full system and data access.</p></div><div class="card"><b>Admin</b><p class="muted">Operational management.</p></div><div class="card"><b>Agent</b><p class="muted">Assigned client workflow.</p></div><div class="card"><b>Assistant</b><p class="muted">Permission-based administrative workflow.</p></div></div></div><div style="height:14px"></div>${empty('No user accounts configured','Authentication and permissions will use the standalone M&H backend.')}`}
function settings(){return `${banner()}<div class="grid two"><div class="card"><h2>Standalone Environment</h2><div class="status">${status('WEB','Web Address','MH.mayerig.com','Reserved',true)}${status('GH','GitHub','JustinMig/MH_CRM','Separate',true)}${status('V','Vercel','New project; old CRM project remains untouched','Separate',true)}${status('DB','Database','New M&H database and storage environment')}</div></div><div class="card"><h2>App Readiness</h2><div class="status">${status('UI','Responsive UI','Touch-first web application shell','Ready',true)}${status('CAM','Camera / Files','Native hooks can be added later','Framework ready',true)}${status('APP','App Shell','Capacitor packaging planned')}${status('','TestFlight / App Store','Signing and submission not configured')}</div></div></div>`}
const pages={dashboard,clients,client,appointments,communications,notifications,documents,medicare:()=>product('medicare'),life:()=>product('life'),retirement:()=>product('retirement'),agents,settings};
function bind(){document.querySelectorAll('[data-route]').forEach(x=>x.onclick=()=>location.hash='#/'+x.dataset.route);document.querySelectorAll('[data-demo]').forEach(x=>x.onclick=()=>alert('No live database is connected yet. No data was changed.'));const m=document.querySelector('#menu'),s=document.querySelector('#sidebar');if(m&&s)m.onclick=()=>s.classList.toggle('open')}
function render(){const r=route();shell(r,pages[r]())}window.addEventListener('hashchange',render);if(!location.hash)location.hash='#/dashboard';render();